SELECT * FROM SQLUser.CT_Sex 

SELECT * FROM SQLUser.DHC_StudentSFC

INSERT INTO SQLUser.DHC_StudentSFC VALUES ('1', '2023-01-01', '张', '1')

SELECT TARAC_TARTAC_DR -> TARTAC_Desc, * FROM SQLUser.DHC_TarAcctCate